name: Slow-Checks

on:
  workflow_call:

jobs:
  build-matrix:
    name: Build Matrix
    uses: ./.github/workflows/matrix.yml
    with:
      matrix_keys_json: '["exasol_versions", "python_versions"]'
    permissions:
      contents: read

  tests:
    name: Integration-Tests (Python-${{ matrix.python_versions }}, Exasol-${{ matrix.exasol_versions}})
    needs:
     - build-matrix
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v10
        with:
          python-version: ${{ matrix.python_versions }}

      - name: Run Tests and Collect Coverage
        run: >
          poetry run -- nox -s test:integration --
          --coverage --db-version ${MATRIX_EXASOL_VERSIONS} --backend=onprem
        env:
          MATRIX_EXASOL_VERSIONS: ${{ matrix.exasol_versions }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: coverage-python${{ matrix.python_versions }}-exasol${{ matrix.exasol_versions }}-slow
          path: .coverage
          include-hidden-files: true
          overwrite: false
